

module.exports = (root) => {
    return {
        swaggerDefinition: {
            info: {
                title: 'Test TMA API',
                version: '1.0.0',
                description: 'Test Express API with autogenerated swagger doc.' +
                    '\n For the routes which are not \'auth\', set Authorization: Bearer + \' \' + uid.' +
                    '\n The two event from socket io are \'users\' and \'messages\'',
            },
            host: 'localhost:3000',
            basePath: '/',
        },
        // List of files to be processes. You can also set globs './routes/*.js'
        apis: [root+'/routes/*/*.route.js'],

    }
}